#!/usr/bin/env bash

# Get the process ID of the Gunicorn master
MASTER_PID=$(pgrep gunicorn)

# Gracefully restart the Gunicorn master
kill -s HUP "$MASTER_PID"

echo "Gunicorn master restarted gracefully"
